# Template for item_config.yaml, a file to configure the iTEM tools

# Paths to data and other information
path:
  # Location of the model database
  model: ../../item_database/item/model

  # Location of the historical database
  historical: ../../item_database/item/historical

  # Location for cached data
  cache: ../../item_database/item/cache

  # Location for the item.log file containing logs from the tools
  # log: .


# Key for the OpenKAPSARC API.
# - Register an account at https://datasource.kapsarc.org/signup/
# - Create a key at https://datasource.kapsarc.org/account/api-keys/
api_key: 796454d0f4ea22fcd654c8bbaf0a9735d1f89993b850900651653eea #saved as item database access key


# No other configuration options are currently recognized