
#Use this file to keep and track different parameters used in the modelthat i havent botheered to put in spreadsheets.


#can edit these to adjust the amount of vehicles in the fleet. it is important to watch stocks per capita, by transport type to udnerstand the impact of these changes.
turnover_rate_parameters_dict:
  turnover_rate_steepness: 0.7

# ECONOMIES_TO_USE_ROAD_ACTIVITY_GROWTH_RATES_FOR_NON_ROAD:
ECONOMIES_TO_USE_ROAD_ACTIVITY_GROWTH_RATES_FOR_NON_ROAD:
  '19_THA': True
  '01_AUS': True
  '02_BD': True
  '03_CDA': True
  '04_CHL': True
  '05_PRC': True
  '06_HKC': True
  '07_INA': True
  '08_JPN': True
  '09_ROK': True
  '10_MAS': True
  '11_MEX': True
  '12_NZ': True
  '13_PNG': True
  '14_PE': True
  '15_RP': True
  '16_RUS': True
  '17_SIN': True
  '18_CT': True
  '20_USA': True
  '21_VN': True
  

ECONOMY_BASE_YEARS_DICT:
  '19_THA': 2020
  '20_USA': 2020
  '01_AUS': 2017
  '02_BD': 2017
  '03_CDA': 2017
  '04_CHL': 2017
  '05_PRC': 2017
  '06_HKC': 2017
  '07_INA': 2017
  '08_JPN': 2017
  '09_ROK': 2017
  '10_MAS': 2017
  '11_MEX': 2017
  '12_NZ': 2017
  '13_PNG': 2017
  '14_PE': 2017
  '15_RP': 2017
  '16_RUS': 2017
  '17_SIN': 2017
  '18_CT': 2017
  '21_VN': 2017
  
ECONOMIES_WITH_MODELLING_COMPLETE:
  '01_AUS': False
  '02_BD': False
  '03_CDA': False
  '04_CHL': False
  '05_PRC': False
  '06_HKC': False
  '07_INA': False
  '08_JPN': False
  '09_ROK': False
  '10_MAS': False
  '11_MEX': False
  '12_NZ': False
  '13_PNG': False
  '14_PE': False
  '15_RP': False
  '16_RUS': False
  '17_SIN': False
  '18_CT': False
  '19_THA': True
  '20_USA': False
  '21_VN': False