
#Use this file to keep and track different parameters used in the model. 
vehicle_gompertz_factors:
  car: 1
  lt: 1
  suv: 1
  bus: 5
  2w: 0.5
  lcv: 30
  mt: 60
  ht: 90
#can edit these to adjust the amount of vehicles in the fleet. it is important to watch stocks per capita, by transport type to udnerstand the impact of these changes.
turnover_rate_parameters_dict:
  turnover_rate_steepness: 0.7

# ECONOMIES_TO_USE_ROAD_ACTIVITY_GROWTH_RATES_FOR_NON_ROAD:
ECONOMIES_TO_USE_ROAD_ACTIVITY_GROWTH_RATES_FOR_NON_ROAD:
  '19_THA': False
  '01_AUS': False
  '02_BD': False
  '03_CDA': False
  '04_CHL': False
  '05_PRC': False
  '06_HKC': False
  '07_INA': False
  '08_JPN': False
  '09_ROK': False
  '10_MAS': False
  '11_MEX': False
  '12_NZ': False
  '13_PNG': False
  '14_PE': False
  '15_RP': False
  '16_RUS': False
  '17_SIN': False
  '18_CT': False
  '20_USA': False
  '21_VN': False
  

ECONOMY_BASE_YEARS_DICT:
  '19_THA': 2020
  '20_USA': 2017
  '01_AUS': 2017
  '02_BD': 2017
  '03_CDA': 2017
  '04_CHL': 2017
  '05_PRC': 2017
  '06_HKC': 2017
  '07_INA': 2017
  '08_JPN': 2017
  '09_ROK': 2017
  '10_MAS': 2017
  '11_MEX': 2017
  '12_NZ': 2017
  '13_PNG': 2017
  '14_PE': 2017
  '15_RP': 2017
  '16_RUS': 2017
  '17_SIN': 2017
  '18_CT': 2017
  '21_VN': 2017
#   vehicle_gompertz_factors = {'car':1,'lt':1,'suv':1,'bus':5,'2w':0.5, 'lcv':20, 'mt': 30, 'ht': 30}
# turnover_rate_parameters_dict = {'turnover_rate_steepness':0.5,'std_deviation_share':0.1,'midpoint_new':12.5,'midpoint_old':25}
# #tried std_deviation_share = 0.25, turnover_rate_steepness = 0.7, midpoint_new = 12.5, midpoint_old = 17.5 #old vehicles never left the fleet once we reached 80% ev stock share
# # tried std_deviation_share = 0.5, turnover_rate_steepness = 0.7, midpoint_new = 12.5, midpoint_old = 17.5 #WAS TOO STEEP